{
  perform: true,
  commands:
    [
      {
        type: "comment",
        name: "findDuplicates",
        allowUsers: ["zurex"],
        action: "comment",
        comment: "Potential duplicates:\n${potentialDuplicates}",
      },
    ],
}
